-- Generated by WhoDidIt's tools\WhoDidIt-Sync - do not edit.
-- ChronicleCompanion by Emyrk: https://github.com/Emyrk/ChronicleCompanion (commit b367dfe17d1183a43552d3985cad6362c7051457)
-- savedvariables: ChronicleCompanionDB
-- savedvariablespercharacter: ChronicleCompanionCharDB
-- file: util.lua
-- file: file.lua
-- file: minimap.lua
-- file: advancedlogging\core.lua
-- file: advancedlogging\units.lua
-- file: advancedlogging\combatant.lua
-- file: advancedlogging\talents.lua
-- file: advancedlogging\config.lua
-- file: core.lua
-- file: debug.lua
-- file: slash.lua
-- file: init.lua
WDI_CHRON_VERSION = "0.38"
WDI_CHRON_COMMIT = "b367dfe17d1183a43552d3985cad6362c7051457"
WDI_CHRON_DATE = "2026-10-05"
